name: Go

on: push

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
          - "1.15"
          - "1.16"
          - "1.17"
          - "1.18"
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go }}

    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test
